### ISSUE TITLE
Keyboard layout in Gnome 3.14

### ISSUE THREAD

**Issue by Dreadeath** [linvinus/AltYo#16]
When unhide Altyo, it doesn`t respect setting of layout for each window (not global), Altyo uses layout of last active window:

1. Type something in English in Altyo, hide it
2. Type something in other window (e.g. browser) in other language
3. Unhide Altyo, it uses that last language and not English.

Also almost on every action (unhide, change tab etc.) with Altyo I see this in logs:
`org.gnome.Caribou.Daemon[23589]: ** (caribou:23703): WARNING **: daemon.vala:102: unhandled editable widget: Terminal`
Don`t know if that related though :-\

**Comment by linvinus** [comment]
Sorry, seems that impossible resolve this bug from altyo side.
```
			/* BUG:#16
			 * When unhide Altyo, it doesn`t respect setting of layout for each window (not global)...
			 * core problem:
			 * 1) xwindow have only NormalState|IconicState|WithdrawnState(unmaped)
			 * 2) libwnck sends "window-closed" signal for unmaped window
			 * 3) xfce4-xkb-plugin remove windowid from internal list as it think window is closed
			 * chain is follow:
			 * window.hide()->WithdrawnState->Unmap->libwnck=>"window-closed"->xfce4-xkb-plugin = forgot window keyboard layout.
			 * same problem in gnome3.
			 * */
```
As a workarund for that we may use window.iconify(),
but in that case some window managers will show minimization animations (BUG #19) (i.e. metacity)
seems that this is fundamental Xwindow/window_managers problem.

**Comment by Dreadeath** [comment]
Can you make an option that set layout every time altyo window appears (hotkey pressed) as workaround?

**Comment by linvinus** [comment]
Ok, there is new attempt  to fix this bug. please try it. (should restore layout after hide/show)

**Comment by Dreadeath** [comment]
Hi, sorry for late answer, nothing changed as far as I can see :-\ Maybe I have to toggle some options?

**Comment by Dreadeath** [comment]
Hm, just updated Gnome to 3.16 and now this works :) Don`t know why, maybe because of some extensions are being disabled after update. Thanks.

**Comment by linvinus** [comment]
ok, i suppose it resolved
