### ISSUE TITLE
Копирование изображения под терминалом

### ISSUE THREAD

**Issue by neronmoon** [linvinus/AltYo#17]
![1](https://cloud.githubusercontent.com/assets/486922/4843478/aa3b6708-6032-11e4-83b5-12105b145bc4.jpg)
![2](https://cloud.githubusercontent.com/assets/486922/4843480/ad95c48e-6032-11e4-9bc8-2901dbbd1a79.jpg)

При втором и последующих вызовах терминала по горячей клавише показывается не терминал, а копия изображения под ним

**Comment by linvinus** [comment]
Core problem was in animation speed, it was too fast, as the result the evil bug was happens.
since 95764ebb2419584bffe7fe0c433b463ef96ebd6f should be completely resolved 
will be available in 0.4~rc14

**Comment by linvinus** [comment]
neronmoon, если есть возможность можете проверить? есть ли этот баг в последней git версии?
я проверил в debian 7, ubuntu 12.10, ubuntu 14.04 везде работает, пока считаю исправленным.
если баг проявится откройте его снова, спасибо.
