### ISSUE TITLE
No transparency when maximize

### ISSUE THREAD

**Issue by guilhem** [linvinus/AltYo#20]
Add ability to remove transparency when full-screen / maximize

**Comment by linvinus** [comment]
Hi! please explain an example of using? 
which options you are using in normal mode?

**Comment by guilhem** [comment]
Hi @linvinus 

Today I'm using Altyo with: width 90, height 50 and background opacity 0,80.

I'm really happy with it (I was using before: guake, terra, tilda, final-term).

But sometime I want to focus on my work, and when I mximize/full-screen Altyo I would like to have some custom settings. Must important of them is opacity 1, but maybe also another set of color.

**Comment by linvinus** [comment]
Thanks for description, i don't want make special option for that special case, i think it should be configurable in css, but right now vte doesn't support that. i will think about that.

**Comment by linvinus** [comment]
with the latest git version you may use following style to remove transparency when full-screen / maximize
(i hope you are talking about true transparency)
```
.window_maximized AYTerm,.window_maximized HVBox,.window_maximized #quick_options_notebook{
-AYTerm-bg-color: #000000;
background-color: #000000;
}
```

**Comment by guilhem** [comment]
@linvinus cool! I will have a look to it ASAP :)

Side question: do you plan to put a daily builded ppa available :angel: (I can help on this part)

**Comment by guilhem** [comment]
@linvinus Thanks, it works like a charm :)
