### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by orschiro** [linvinus/AltYo#21]
Hi @linvinus,

Many thanks for this promising drop down terminal! 

I wanted to use it on the following system:
```
openbox 3.5.2-7
altyo-git 0.4_rc12.1.r17.g131e481-1
3.18.2-2-ARCH 64-bit
vte 0.28.2-5
vte-common 0.38.3-1
vte3 0.38.3-1
```

However, it crashes with a segmentation fault:
```
❯ altyo

** (altyo:14801): WARNING **: altyo_config.vala:420: Key file does not have key 'profile_version'

** (altyo:14801): WARNING **: altyo_config.vala:513: Key file does not have key 'distrib_id'

** (altyo:14801): WARNING **: altyo_config.vala:358: Key file does not have key 'reduce_memory_usage'

** (altyo:14801): WARNING **: altyo_config.vala:358: Key file does not have key 'window_allow_remote_control'

** (altyo:14801): WARNING **: altyo_config.vala:358: Key file does not have key 'debug'
[1]    14801 segmentation fault (core dumped)  altyo
```

Any idea why it is crashing?

Thanks!

Robert

**Comment by samanx** [comment]
I have the same problem.
'''$ altyo 

** (altyo:1802): WARNING **: altyo_config.vala:420: Key file does not have key 'profile_version'

** (altyo:1802): WARNING **: altyo_config.vala:513: Key file does not have key 'distrib_id'

** (altyo:1802): WARNING **: altyo_config.vala:358: Key file does not have key 'reduce_memory_usage'

** (altyo:1802): WARNING **: altyo_config.vala:358: Key file does not have key 'window_allow_remote_control'

** (altyo:1802): WARNING **: altyo_config.vala:358: Key file does not have key 'debug'
Segmentation fault (core dumped)
'''

**Comment by linvinus** [comment]
Hi!
Please recompile as follow (enable debugging information)
```
$ VALA_FLAGS =" -g  -X -O0" make
```
then run in gdb
```
$gdb ./altyo
>run
```
after segmentation fault, run backtrace and share result
```
>bt
```

**Comment by linvinus** [comment]
Resolved.

**Comment by orschiro** [comment]
Thanks for the quick fix!
On 01/24/2015 11:55 AM, linvinus wrote:
>
> Resolved.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/linvinus/AltYo/issues/21#issuecomment-71310842>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by linvinus** [comment]
no problem
