### ISSUE TITLE
Ломающийся биндинг на F1

### ISSUE THREAD

**Issue by FRiMN** [linvinus/AltYo#27]
У меня в качестве показа/скрытия окна стоит F1. Так, через какое-то время биндинг на эту клавишу отваливается: видно, что при нажатии на F1 фокус с текущего окна пропадает (возможно, уходит на скрытое окно altyo), но окно altyo не показывается.
Тоже самое и со stand-alone.

**Comment by FRiMN** [comment]
Как оказалось, это не связано с конкретной комбинацией клавиш, но связано как-то с Chromium'ом.
Конфиг: http://pastebin.com/n542j4S1

**Comment by linvinus** [comment]
Здравствуйте.
в режиме stand-alone главная клавиша отключена.

в режиме выпадающего окна
другое приложение может перебиндить(перехватывать) главную клавишу, поэтому конфликты нужно исключать вручную.

Но попробуйте после того как перестала работать клавиша запустить /usr/bin/altyo без параметров, это аналог нажатия главной клавиши, если окно не появится то проблема не в клавишах, есть сложный глюк, толи в GTK толи в X, окно не отрисовывается, оно появляется и даже можно вызвать меню правой кнопкой мыши но содержимое не отображается (прозрачное)
Этот глюк у меня проявляется очень редко поэтому пока не разобрался.

**Comment by FRiMN** [comment]
/usr/bin/altyo ничего не даёт, но возможно просто пропадает фокус. Попытка открытия терминала клавишей срабатывает только с третьего раза (окно при этом невидимо, а по высоте очень маленькое, меню не вызывается), закрытие -- как и должно -- с первого.

**Comment by linvinus** [comment]
Понятно, этот баг уже описан тут #25 
чтобы не было дублей, эту ветку закрываю.
