### ISSUE TITLE
Feature: setting for closing tab on shell termination

### ISSUE THREAD

**Issue by zhulik** [linvinus/AltYo#28]
Hi.
I use guake and yakuake early so i used to press ctrl+d wich close my zsh session and close emulator close tab after it, but AltYo just reload shell. May be it is a good idea to allow user to customize this behavior?

**Comment by linvinus** [comment]
Hi! 
in settings, under "Terminal" section, disable "Auto restart shell"

**Comment by zhulik** [comment]
Oops, sorry, but i really overlook it=)
