### ISSUE TITLE
Unexpected shrink into small line

### ISSUE THREAD

**Issue by zhum** [linvinus/AltYo#30]
Hello! I use altyo and really love it :) On my ubuntu station it works fine, but on my mint 17 (and now 17.2) some times (I cannot guess when) it becomes like very thin line and I cannot access tabs or anything. All processes in tabs work. Focus is taken if I press F12. But I cannot return right size. Fullscreen mode does not work - size keeps small...
Window switcher applet "sees" altyo - here is a screenshot. Red arrow shows altyo window in applet, blue - only the visible line of real altyo window.
![altyo-bug](https://cloud.githubusercontent.com/assets/336958/9448088/4a3954a8-4aa3-11e5-9c1e-c799502ee440.png)

**Comment by linvinus** [comment]
sorry about that. but this bug is not new :(
Please follow this bug #25

**Comment by zhum** [comment]
I saw this bug, but here I see, that window is not transparent, but really shrunk, so I created new :) If it is really the same bug I will follow it for successful resolve!
Anyway thank you for really great terminal. If it could save it's sessions EVERY time it would be perfect!

**Comment by linvinus** [comment]
shrunk or transparent it depends on window manager/compositing manager, i'm sure it the same bug (unfortunately)
