### ISSUE TITLE
Segmantation fauilf on build with new gnome 3.18 libs

### ISSUE THREAD

**Issue by thankjura** [linvinus/AltYo#31]
jura@ultrahost ~ $ altyo

(altyo:19530): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

** (altyo:19530): WARNING **: altyo_config.vala:447: Key file does not have key 'profile_version' in group 'profile0'

** (altyo:19530): WARNING **: altyo_config.vala:540: Key file does not have key 'distrib_id' in group 'profile0'

** (altyo:19530): WARNING **: altyo_config.vala:385: Key file does not have key 'reduce_memory_usage' in group 'profile0'

** (altyo:19530): WARNING **: altyo_config.vala:385: Key file does not have key 'window_allow_remote_control' in group 'profile0'

** (altyo:19530): WARNING **: altyo_config.vala:385: Key file does not have key 'debug' in group 'profile0'

(altyo:19530): GLib-GObject-CRITICAL **: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(altyo:19530): GLib-GObject-WARNING **: /var/tmp/portage/dev-libs/glib-2.46.0/work/glib-2.46.0/gobject/gtype.c:4268: type id '0' is invalid

(altyo:19530): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
zsh: segmentation fault  altyo

**Comment by linvinus** [comment]
Hi!
please follow  these instructions https://github.com/linvinus/AltYo/issues/21#issuecomment-71305267

**Comment by y2kbadbug** [comment]
There really isn't any instructions here.  I am experiencing a similar problem.

Can't open libreoffice due to:

(soffice:12241): GLib-GObject-CRITICAL **: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
(soffice:12241): GLib-GObject-WARNING **: gtype.c:4268: type id '0' is invalid
(soffice:12241): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
Application Error

**Comment by thankjura** [comment]
jura@ultrahost ~/Desktop/AltYo $ gdb ./altyo 
GNU gdb (Gentoo 7.10 vanilla) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./altyo...done.
(gdb) bt
No stack.
(gdb) run
Starting program: /home/GrandMaster/Desktop/AltYo/altyo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffecb09700 (LWP 29374)]
[New Thread 0x7fffe7fff700 (LWP 29375)]

** (altyo:29370): WARNING **: altyo_config.vala:447: Файл ключей не содержит ключа «profile_version» в группе «profile0»

** (altyo:29370): WARNING **: altyo_config.vala:540: Файл ключей не содержит ключа «distrib_id» в группе «profile0»

** (altyo:29370): WARNING **: altyo_config.vala:385: Файл ключей не содержит ключа «reduce_memory_usage» в группе «profile0»

** (altyo:29370): WARNING **: altyo_config.vala:385: Файл ключей не содержит ключа «window_allow_remote_control» в группе «profile0»

** (altyo:29370): WARNING **: altyo_config.vala:385: Файл ключей не содержит ключа «debug» в группе «profile0»

(altyo:29370): GLib-GObject-CRITICAL **: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(altyo:29370): GLib-GObject-WARNING **: /var/tmp/portage/dev-libs/glib-2.46.0/work/glib-2.46.0/gobject/gtype.c:4268: type id '0' is invalid

(altyo:29370): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6dbe498 in gtk_widget_style_get_valist () from /usr/lib64/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff6dbe498 in gtk_widget_style_get_valist () from /usr/lib64/libgtk-3.so.0
#1  0x00007ffff6dbe774 in gtk_widget_style_get () from /usr/lib64/libgtk-3.so.0
#2  0x0000000000432bd6 in ay_term_get_style_color (self=0xb20b80, name=0xc809c0 "palette-0", color=0x7fffffffc110) at /home/GrandMaster/Desktop/AltYo/altyo_terminal.vala:568
#3  0x0000000000432f59 in ay_term_gen_colors (self=0xb20b80, tct=0x9fae30) at /home/GrandMaster/Desktop/AltYo/altyo_terminal.vala:583
#4  0x000000000043353d in ay_term_update_style (self=0xb20b80) at /home/GrandMaster/Desktop/AltYo/altyo_terminal.vala:621
#5  0x000000000043894d in vt_terminal_configure (self=0x7ab240, my_conf=0x960be0) at /home/GrandMaster/Desktop/AltYo/altyo_terminal.vala:1099
#6  0x00000000004342c9 in vt_terminal_construct (object_type=10916240, my_conf=0x960be0, notebook=0x9ab1c0, tab_index=0, session_command=0x0, session_path=0x0, 
    on_child_exit=0x456214 <____lambda92__on_child_exit_call_back>, on_child_exit_target=0x7ab0a0) at /home/GrandMaster/Desktop/AltYo/altyo_terminal.vala:691
#7  0x00000000004343c2 in vt_terminal_new (my_conf=0x960be0, notebook=0x9ab1c0, tab_index=0, session_command=0x0, session_path=0x0, 
    on_child_exit=0x456214 <____lambda92__on_child_exit_call_back>, on_child_exit_target=0x7ab0a0) at /home/GrandMaster/Desktop/AltYo/altyo_terminal.vala:649
#8  0x00000000004566b9 in ay_object_add_tab (self=0x7ab0a0, session_command=0x0, session_path=0x0, on_exit=0x0, on_exit_target=0x0) at /home/GrandMaster/Desktop/AltYo/altyo_window.vala:1581
#9  0x00000000004554cf in ay_object_create_tabs (self=0x7ab0a0) at /home/GrandMaster/Desktop/AltYo/altyo_window.vala:1494
#10 0x0000000000447695 in _ay_object_create_tabs_gsource_func (self=0x7ab0a0) at altyo_window.vala.c:1662
#11 0x00007ffff535a1fd in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#12 0x00007ffff535a5f0 in ?? () from /usr/lib64/libglib-2.0.so.0
#13 0x00007ffff535a912 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#14 0x00007ffff6c70795 in gtk_main () from /usr/lib64/libgtk-3.so.0
#15 0x000000000041b9d6 in __lambda140_ (_data1_=0x73ba00) at /home/GrandMaster/Desktop/AltYo/main.vala:550
#16 0x000000000041ba46 in ___lambda140__g_application_startup (_sender=0x7470f0, self=0x73ba00) at /home/GrandMaster/Desktop/AltYo/main.vala:505
#17 0x00007ffff5663f45 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#18 0x00007ffff5675e11 in ?? () from /usr/lib64/libgobject-2.0.so.0
#19 0x00007ffff5680388 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#20 0x00007ffff568057f in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#21 0x00007ffff595ef82 in g_application_register () from /usr/lib64/libgio-2.0.so.0
#22 0x00007ffff595fb12 in g_application_run () from /usr/lib64/libgio-2.0.so.0
#23 0x000000000041d322 in _vala_main (args=0x7fffffffd908, args_length1=1) at /home/GrandMaster/Desktop/AltYo/main.vala:553
#24 0x000000000041d3be in main (argc=1, argv=0x7fffffffd908) at /home/GrandMaster/Desktop/AltYo/main.vala:333
(gdb) q

**Comment by zhulik** [comment]
I have the same issue, building from git, Arch, Gnome 3.18
```
#0  0x00007ffff6db8f20 in gtk_widget_style_get_valist () from /usr/lib/libgtk-3.so.0
#1  0x00007ffff6db9204 in gtk_widget_style_get () from /usr/lib/libgtk-3.so.0
#2  0x0000000000431bcf in ay_term_get_style_color (self=0xb04780, name=0xbce7d0 "palette-0", color=0x7fffffffc920) at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_terminal.vala:568
#3  0x0000000000431ec9 in ay_term_gen_colors (self=0xb04780, tct=0x94ad30) at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_terminal.vala:583
#4  0x00000000004324fd in ay_term_update_style (self=0xb04780) at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_terminal.vala:621
#5  0x0000000000437618 in vt_terminal_configure (self=0x9b8a50, my_conf=0x7dc1c0) at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_terminal.vala:1099
#6  0x00000000004331b5 in vt_terminal_construct (object_type=9844896, my_conf=0x7dc1c0, notebook=0x7b11d0, tab_index=0, session_command=0x0, session_path=0x0, on_child_exit=0x453eca <____lambda92__on_child_exit_call_back>, on_child_exit_target=0x9b88b0)
    at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_terminal.vala:691
#7  0x0000000000433291 in vt_terminal_new (my_conf=0x7dc1c0, notebook=0x7b11d0, tab_index=0, session_command=0x0, session_path=0x0, on_child_exit=0x453eca <____lambda92__on_child_exit_call_back>, on_child_exit_target=0x9b88b0)
    at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_terminal.vala:649
#8  0x0000000000454360 in ay_object_add_tab (self=0x9b88b0, session_command=0x0, session_path=0x0, on_exit=0x0, on_exit_target=0x0) at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_window.vala:1581
#9  0x00000000004531f1 in ay_object_create_tabs (self=0x9b88b0) at /home/zhulik/Downloads/altyo-git/src/altyo-git/altyo_window.vala:1494
#10 0x0000000000445aa7 in _ay_object_create_tabs_gsource_func (self=0x9b88b0) at altyo_window.vala.c:1662
#11 0x00007ffff53e6c7a in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#12 0x00007ffff53e7020 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0x00007ffff53e7342 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff6c69545 in gtk_main () from /usr/lib/libgtk-3.so.0
#15 0x000000000041b4b9 in __lambda140_ (_data1_=0x6f2a00) at /home/zhulik/Downloads/altyo-git/src/altyo-git/main.vala:550
#16 0x000000000041b516 in ___lambda140__g_application_startup (_sender=0x7240f0, self=0x6f2a00) at /home/zhulik/Downloads/altyo-git/src/altyo-git/main.vala:505
#17 0x00007ffff56bb035 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff56cd081 in ?? () from /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff56d5e1c in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff56d614f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff59a5e12 in g_application_register () from /usr/lib/libgio-2.0.so.0
#22 0x00007ffff59a68f6 in g_application_run () from /usr/lib/libgio-2.0.so.0
#23 0x000000000041cd39 in _vala_main (args=0x7fffffffe218, args_length1=1) at /home/zhulik/Downloads/altyo-git/src/altyo-git/main.vala:553
#24 0x000000000041cdb2 in main (argc=1, argv=0x7fffffffe218) at /home/zhulik/Downloads/altyo-git/src/altyo-git/main.vala:333
```

**Comment by willemw12** [comment]
Me too, after upgrade and rebuild:

    upgraded gtk3 (3.16.7-1 -> 3.18.1-1)                                                                    
    upgraded vte-common (0.40.2-1 -> 0.42.0-1)                                                                           
    upgraded vte (0.28.2-6 -> 0.28.2-7)                                                                     
    upgraded vte3 (0.40.2-1 -> 0.42.0-1)

**Comment by linvinus** [comment]
It seems that GTK3 broke parsing CSS styles, again.
I will check that theory today later.

**Comment by willemw12** [comment]
Downgrading gtk3 can be used as a workaround.

**Comment by linvinus** [comment]
similar issue https://bbs.archlinux.org/viewtopic.php?id=203512
i believe these bug is in GTK, not in altyo
i can nothing todo with that

**Comment by thankjura** [comment]
bug dissaper after rebuild gtk+-3.18.1 with this patch https://git.gnome.org/browse/gtk+/commit/?id=bddc524cd84b76d1c25c7700eca9d3a25db30cf6

**Comment by zhulik** [comment]
ArchLinux, latest GTK3 3.18.2-1 - works fine.

**Comment by linvinus** [comment]
thank you for the information!
