### ISSUE TITLE
Ctrl+Tab for terminal_tab_next

### ISSUE THREAD

**Issue by suedi** [linvinus/AltYo#33]
In many applications Ctrl+Tab is used for next tab.
I have this in my muscle-memory

This does not seem to be allowed in Altyo

Could it be done?

**Comment by linvinus** [comment]
confirm, but it seems that this is not allowed in GTK3, i will try to find solution 

as workaround you may setup this hotkey manually in config.ini file

**Comment by suedi** [comment]
I tried to do it manually  in config file but couldn't get it to work
```bash
terminal_tab_next=<Primary><TAB>
terminal_tab_next=<Primary><Tab>
terminal_tab_next=<Primary><tab>
terminal_tab_next=<Primary>TAB
terminal_tab_next=<Primary>Tab
terminal_tab_next=<Primary>tab
```

What should I use when manually hacking it in?

**Comment by linvinus** [comment]
hmm, now setup the ctrl+tab keybind is possible, but it not working
similar bug https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/162000

**Comment by suedi** [comment]
thats alarming. the bug reported a long time ago but
wasn't fixed.

Anyway simargls taeni terminal work with ctrl+tab

It also uses gtk3

checkout

https://github.com/simargl/vala-apps/blob/master/tae.ni/src/taeni.vala

**Comment by suedi** [comment]
Yeah now it really works.

This is going to make a lot of users happy.
They are accustomed to this key combination from firefox and others.

For me it's so important I would probably choose some other terminal if
this didn't work

Good F***ing Job! :+1:
