### ISSUE TITLE
How to close/hide "Quick Settings" ?

### ISSUE THREAD

**Issue by suedi** [linvinus/AltYo#34]
When do right click in Altyo and choose

> Quick Settings --> Terminal Settings

I then choose what values I want but seem unable to close it?

The only way, I found, was to open full settings and then close
which closes both "settings" and "quick settings" 

How was it meant to be done?

**Comment by linvinus** [comment]
the close button is on far-right side

**Comment by suedi** [comment]
Yeah now I see it, That wasn't really obvious

Why doesn't it say "close"? t

Takes up to much space?

Could you not have like a small picture on it that suggests a closing action?

**Comment by linvinus** [comment]
suedi, hi!
can you check latest git version?
is it user-friendly now?

**Comment by suedi** [comment]
It is more user-friendly now, definetly better than before.

May I ask why you don't want any text on the button like "apply"?

You could also consider a pictogram.

My reasoning for this is that it could be thought of as not a button but to "fill out" the tab bar 
for a first time user.


I think it is OK but not 100% self-explanatory.
