### ISSUE TITLE
Settings and maximized window

### ISSUE THREAD

**Issue by suedi** [linvinus/AltYo#35]
When I run altyou in standalone mode and have my window maximized.
Then I open settings and press apply it will un-maximize the window.

If think altyo should retain window state when leaving settings view with apply

**Comment by linvinus** [comment]
from one side your logic is correct, but what if user want to change from full-screen to normal window, if previously was full screen state?
so, after you press apply  button, altyo reload all settings, include window state.
I don't think it is real bug, may be not the best behavior, but this  behavior more transparent and simple from programmers side.
changing altyo settings it is not every-day function, so i don't think it is really matter

**Comment by suedi** [comment]
OK so you reload all info from config-file and also the start-size of window.

Yeah I can see this from your point of you and agree's that your way is better.

closing...
