### ISSUE TITLE
environment when starting in standalone mode

### ISSUE THREAD

**Issue by suedi** [linvinus/AltYo#36]
When starting altyo --standalone and then type command 
env in that terminal I get

```bash
TERM=xterm
GTK2_RC_FILES=/.gtkrc-2.0
PWD=/root
SHLVL=1
COLORTERM=altyo_real
_=/usr/bin/env
```
Here things like DISPLAY and PATH that my system uses
are not included or processed

When I do the same in dropdown mode and type env I get full environment
and this is what I would like in --standalone as well

```bash
LC_PAPER=C
LC_ADDRESS=C
LC_MONETARY=C
HOSTNAME=alphaos
QT_STYLE_OVERRIDE=gtk
TERM=xterm
VTE_VERSION=4002
XDG_MENU_PREFIX=gnome-
SHELL=/usr/bin/bash
GTK2_RC_FILES=/root/.gtkrc-2.0
WINDOW_MANAGER=openbox
CURL_CA_BUNDLE=/etc/ca-certificates/extracted/ca-bundle.trust.crt
LC_NUMERIC=C
LC_ALL=C
USER=root
LC_TELEPHONE=C
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
MAIL=/var/spool/mail/root
PATH=/usr/bin:/usr/local/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
LC_MESSAGES=C
LC_IDENTIFICATION=C
LC_COLLATE=C
PWD=/root
EDITOR=geany
LANG=C
TZ=:/etc/localtime
LC_MEASUREMENT=C
SHLVL=5
HOME=/root
LOGNAME=root
LC_CTYPE=C
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-VTr59mefIL,guid=ee5adf191e1f03d20c98eba656240cc4
BROWSER=web-browser
WINDOWPATH=4
DISPLAY=:0
XDG_RUNTIME_DIR=/tmp
LC_TIME=C
COLORTERM=altyo_real
LC_NAME=C
_=/usr/bin/env
```

**Comment by linvinus** [comment]
By default only following variables will excluded
`this.my_conf.get_string("terminal_exclude_variables","^(COLUMNS|LINES|GNOME_DESKTOP_ICON|COLORTERM|WINDOWID)$"
`
if you don't change this setting, then problem is in your bashrc file, or may be you run different shells i.e. bash in dropdown mode zsh in standalone mode
standalone mode have its own configuration file

**Comment by suedi** [comment]
I was using the same shell for both standalone and dropdown mode
I was using the same .bashrc for both standalone and dropdown mode

I listened to your advice and did a cp -f config.ini config-standalone.ini
and then I got the complete environtment.

But which option is it that tells altyo to crop environment then??

here is my config file for standalone

https://www.dropbox.com/s/ewu40kq9trld470/config-standalone.ini?dl=1

**Comment by suedi** [comment]
found the difference

I had 
```bash
terminal_exclude_variables=
```
vs
```bash

```bash
^(COLUMNS|LINES|GNOME_DESKTOP_ICON|COLORTERM|WINDOWID)$
```

I think this was an accident to clear this field.

Maybe you should check in code if it is set to zero length empty string don't
exclude every variable in environment or is this a feature that gives you 
the possibility to start with clean environment?

**Comment by suedi** [comment]
Good Job, Thanks for that
