### ISSUE TITLE
swedish character Å

### ISSUE THREAD

**Issue by suedi** [linvinus/AltYo#38]
I have tried different text encodings but cannot get swedish character Å to work
in altyo

The other special swedish characters work fine that is
Ä and Ö works fine.

This is not a problem since I don't remember any situation yet where I had a need 
to use that character in terminal.

So this is more to give you the information about it.

**Comment by linvinus** [comment]
i believe with UTF-8 it should working fine.
UTF-8 is default standard encoding for linux.

**Comment by suedi** [comment]
Yeah it solves it but when I slip on the keys there sometimes, quiet often
becomes garbled characters

The command looks visually OK but when it's executed it fails showing
that there was some garbage characters in command.

Felt it happen less often with other encodings.

comment?

**Comment by linvinus** [comment]
hmm, altyo use standard terminal library from gnome project - libvte
so all standard input methods should working fine
there is more about input method https://help.gnome.org/misc/release-notes/3.6/i18n-ibus.html.en
also you may search for problems with input method for your language for linux.
it should be typical problem if it really exist.

**Comment by gammy** [comment]
Swedish user here. Tried and tested(arch AUR, 0.4_rc12.1.r16.g777b7ad-1) both input and output on UTF-8. Works fine for me. If you need more information about my environment, feel free to ask!

**Comment by linvinus** [comment]
gammy, thank you.
for now, i suppose, that problem doesn't exist
