### ISSUE TITLE
Crash on wayland

### ISSUE THREAD

**Issue by zhulik** [linvinus/AltYo#41]
Hi, i did some experiments with Wayland and noticed, that altyo crashes with segfault when i try to run it from Gnome Wayland session, i know that gtk3 and vte3 supports running on wayland, so, i suppose, that problem in altyo code. Can you check it? Any traces, debug info and so on on your request. 

ArchLinux, vte3 0.42.1, gtk3 3.18.5

**Comment by linvinus** [comment]
Thanks for the information, but Wayland doesn't have lot of necessary  functions, for example keyboard grabbing ( XGrabKey or XGrabKeyboard analog).
