### ISSUE TITLE
Terminal output in fullscreen mod

### ISSUE THREAD

**Issue by ten0r** [linvinus/AltYo#42]
In 100% height 100% width mod
1. Execute something like
```
ls -al /usr/lib
```
that cause scroll.
2. Open vim
3. Hide altyo
4. Show altyo (I use shortcut)
5. Exit from vim
Some lines from previous output dissapears.

**Comment by linvinus** [comment]
which version of libvte you have?

**Comment by ten0r** [comment]
vte3 0.42.1-2 from arch repo

**Comment by linvinus** [comment]
ok, thanks for answer
few more questions 

1) is the same problem occurs if you do  following steps?
1. Execute something like `ls -l /usr/lib`
2. Open vim
3. Exit from vim

2) can you compare behavior with gnome-terminal ? it also have full-screen mode

3) is the same problem occurs with vi ?  (not vim)

**Comment by ten0r** [comment]
1. No, only if I hide and show altyo.
2. Sorry there's no hotkey to hide/show terminal, but when I hide all windows using desktop shortcut it works ok. So gnome-terminal don't eat lines.
3. Yes. The same with nano.

More info 14 lines dissapears completely, 15'th line end suggested to input.

**Comment by linvinus** [comment]
ten0r, something similar already has happening with libvte in the past, 
for example https://bugzilla.gnome.org/show_bug.cgi?id=708213

can you compare with previous version of libvte?

with libvte 0.34.9 i don't have such  problem.

**Comment by ten0r** [comment]
Bug introduced between 0.38.4 and 0.39.0. I can't build altyo on 0.43.0+. Bug exists in 0.42.3.

**Comment by linvinus** [comment]
can you create libvte bug report?

**Comment by ten0r** [comment]
Sorry but don't know how to explain this bug, cause I don't know how did actually altyo interacts with vte.

**Comment by linvinus** [comment]
main difference between altyo and gnome-terminal is that when  altyo hides/restores it move vte widget to offscreen window, in that case  content resize in vte could happens.

so, if i correct then same bug should be in this case with gnome-terminal

1. Execute something like `ls -al /usr/lib`
2. Open vim
3. resize gnome-terminal window, a little 
5. Exit from vim

can you check that?

**Comment by ten0r** [comment]
Yes, the problem exists in gnome-terminal.

**Comment by linvinus** [comment]
thanks, i think we can close this bug because problem is in libvte not in altyo.

**Comment by ten0r** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=761097
Posible solutions:
1. Use vte<=0.38.
2. Define height in pixels, not 100% or fullscreen.

**Comment by linvinus** [comment]
thank you for report.
I hope libvte team will solve this bug.
