### ISSUE TITLE
Scrolling feature

### ISSUE THREAD

**Issue by ten0r** [linvinus/AltYo#43]
Please add one page scrolling feature instead of instant scroll to cursor position in scrollbar.

**Comment by linvinus** [comment]
why not use Shift+ PgUP/PgDown ?

**Comment by ten0r** [comment]
Because it's feature request and it is default behavior in many other applications.

**Comment by linvinus** [comment]
feature request is ok, but i'm not sure that understand you correctly.
 
to be more clear, you wish to have scrolling similar to Shift+ PgUP/PgDown, but with scrolling by scroll bar? 

if so, in which application did you seen that, i have never saw such behavior.

also, what you mean by " instant scroll to cursor position in scrollbar." ?
thanks.

**Comment by ten0r** [comment]
Yes like Shift + PgUP/PgDown.
Thunderbird, chromium, libreoffice, guake, gvim, gimp, vlc, gajim. But firefox and gnome-terminal moves screen position to the mouse click position on scrollbar.

**Comment by linvinus** [comment]
ok, i think that understand you, will try to find solution to implement such behavior.

**Comment by linvinus** [comment]
done.
New setting "Scroll by page" under Terminal section in configuration dialog.
Now by default altyo will have new default behavior for scrolling. 

please reopen if you don't agree.
