### ISSUE TITLE
Complete link not detected with Unicode characters

### ISSUE THREAD

**Issue by jarun** [linvinus/AltYo#44]
Noticed this while searching Renée Zellweger with [googler](https://github.com/jarun/googler). Refer the image below:
 
![results](http://i.imgur.com/9cVdzId.png)
  
When hovering on the first result, the full Wikipedia link is not detected (underlined) and when clicked it opens only https://en.wikipedia.org/wiki/Ren in browser.
  
    $ altyo --version
    altyo 0.4_rc17-linvinus1~trusty
    $ cat /etc/issue
    Ubuntu 14.04.4 LTS \n \l
    $ arch
    x86_64

**Comment by linvinus** [comment]
Hi! thank you for report.
But actually according to rfc this symbols must be encoded http://stackoverflow.com/questions/1856785/characters-allowed-in-a-url

But you may adjust regexp so it will include your chars. (settings->additional->regexps->url

i suppose this is not a bug or feature request.

**Comment by jarun** [comment]
Thanks for taking your time to clarify!
