### ISSUE TITLE
AltYo только на одном рабочем столе.

### ISSUE THREAD

**Issue by interact82** [linvinus/AltYo#45]
Здравствуйте.
Хотелось бы иметь настройку для закрепления окна только на одном рабочем столе, плюс задавать конкретно на каком столе будет
закреплен (1,2,3,4...и т.д).

**Comment by linvinus** [comment]
хотелось бы уточнить, речь идёт о виртуальном рабочем столе или о мониторе?

если виртуальный рабочий стол то если этот стол не активен в чём смысл показать altyo на этом столе? 
визуально это выглядит так как будто после нажатия горячей клавиши окно не появилось.
патч я сделал но не могу понять почему это может быть полезно?

**Comment by interact82** [comment]
> речь идёт о виртуальном рабочем столе или о мониторе?

> 

О виртуальном.

Возможно пользы от этого ни какой, не спорю. Просто изучая настройки программы в "Быстрые настройки" есть пункт "Всегда на видимом рабочем столе" вот и появилась такая идея 

> иметь настройку для закрепления окна только на одном рабочем столе, плюс задавать конкретно на каком столе будет
