### ISSUE TITLE
Pressing hotkey before animation ends prevents window from showing

### ISSUE THREAD

**Issue by p3732** [linvinus/AltYo#46]
When the hotkey is pressed before the animation has ended, AltYo crashes. This seems to be independent of "Auto hide on focus lost" and hotkey binding. All that is needed is to set animation to true.
Version: altyo 0.4_rc17-linvinus1 7ab370b  (current git version)
gtk3-3.18.9-1
gnome-shell-3.18.4-1
Arch 64Bit

**Comment by linvinus** [comment]
please run altyo from console with `-d` option, then share result.
this bug is something new

**Comment by p3732** [comment]
Did so, the comments starting with ### were added by me, so you can easier figure out what's wrong. I personally don't see anything though.
[hotkey_report.txt](https://github.com/linvinus/AltYo/files/171024/hotkey_report.txt)
config.ini (renamed to .txt bc github doesn't like .ini files)
[config.txt](https://github.com/linvinus/AltYo/files/171025/config.txt)

**Comment by linvinus** [comment]
hi, thank you, but i don't see any crush (segfaults),
did you mean by "crush" transparent window? (at the moment of "### "showing" which does not actually show")

**Comment by p3732** [comment]
Whoops, yes, that was wrong phrasing. What I meant is that the functionality crashes. Well yes, the window is transparent. Or not there. Kind of difficult to tell.

**Comment by linvinus** [comment]
ok, then you are talking about known bug #25
