### ISSUE TITLE
Allow cursor color change

### ISSUE THREAD

**Issue by cpriego** [linvinus/AltYo#49]
Hi, I've been using your terminal for quite a while and it is amazing.

Now I come here with a feature request: adding a setting to **allow for cursor color change.**

Here's an image with an example of this
![Image of Terminal](http://www.image-share.com/upload/3204/7.png)

**Comment by linvinus** [comment]
Hi! Thanks for your feedback!
Cursor color it is property of your bash/zsh prompt settings, from terminal side cursor it is usual character, like any others

http://unix.stackexchange.com/questions/55423/how-to-change-cursor-shape-color-and-blinkrate-of-linux-console

**Comment by linvinus** [comment]
this feature does not related to altyo , closed
