### ISSUE TITLE
Dedicated standalone mode via the config

### ISSUE THREAD

**Issue by kmf** [linvinus/AltYo#54]
Is there a way to always start the terminal in "standalone" mode, and can that be set via the config file? 

I would like this feature.

**Comment by linvinus** [comment]
hi.
you should have installed two desktop files altyo.desktop and altyo_standalone.desktop
second file will launch altyo in standalone mode, also you may use ctrl+shift+N to launch new standalone window from current instance

**Comment by kmf** [comment]
Thanks!
