### ISSUE TITLE
AltYo DropDown Segfault error

### ISSUE THREAD

**Issue by Sandman007** [linvinus/AltYo#55]
Hello,

I am using the AltYo DropDown Terminal on Manjaro XFCE 16.06 (Arch Base). I am receiving a Segfault error when Dropping the dropdown terminal after a period of inactivity,

AltYo Version: 0.4_rc19-linvinus1 315cbf6

What steps will reproduce the problem?
1. Launch Altyo
2. Drop the terminal down then roll it back up
3. Come back after some inactivity (Seems sporadic)
4. Altyo Segfaults and I then must relaunch Altyo to continue using it.

DMESG:
`altyo[2072]: segfault at 7ffce51e9ff8 ip 00007f69b9283b04 sp 00007ffce51ea000 error 6 in libgtk-3.so.0.2000.3[7f69b911e000+6cc000]`

This is my first time submitting a bug report so let me know if I can provide anything else that might be useful

Sandman007

**Comment by linvinus** [comment]
please compile with debugging symbols and run in gdb

$ cd /src
$ export VALA_FLAGS=" -g --save-temps -X -O0"
$ make
$ gdb ./altyo
run -d

after Segfault in gdb call
bt

then share results
