### ISSUE TITLE
Font looks really weird

### ISSUE THREAD

**Issue by z3ntu** [linvinus/AltYo#56]
![fish -home-luca_053](https://cloud.githubusercontent.com/assets/3768500/14948864/1d0f6e0a-1045-11e6-9f01-a7c6a2787550.png)

I tried using "Source Sans Pro", "Noto Sans Regular" and more, all look really bad. Default font was "None" which looked acceptable (not overlayed), but still bad.

**Comment by linvinus** [comment]
this is not a bug, you must use  Monospaced fonts like
https://github.com/adobe-fonts/source-code-pro
`Noto Sans Mono CJK {JP, KR, SC, TC} `
