### ISSUE TITLE
Altyo ignores font color settings

### ISSUE THREAD

**Issue by AKorezin** [linvinus/AltYo#60]
Terminal font foreground color setting ignored.
If I set font color to FFFFFF it will always reset it to AAAAAA.
Also after applying settings color palette always resets to default one.
If I change VTToggleButton color I need to press apply button twice to change the color.

**Comment by linvinus** [comment]
hi, how you change the settings?
settings->advanced->application style->text color
when color will be changed you will see new color settings in css style.

```@define-color ayterm-fg-color #FFFFFF;```

**Comment by AKorezin** [comment]
Recompiled against another vte version and everything work as expected. It seems the bug in some versions of vte.

**Comment by Vistaus** [comment]
I have the same problem. I can set whatever color but Altyo ignores all of the colors and resets to the default colors.
