### ISSUE TITLE
Системный шрифт

### ISSUE THREAD

**Issue by mrlioncub** [linvinus/AltYo#64]
Хотелось в выборе шрифтов использовать системный шрифт.

**Comment by linvinus** [comment]
а сейчас что мешает его выбрать?

**Comment by mrlioncub** [comment]
Я не знаю какой из всего списка системный.

**Comment by mrlioncub** [comment]
Не работает:

$ altyo --version
altyo 0.4_rc19-linvinus1~xenial  
License GPLv3+

# apt-cache show altyo
Package: altyo
Priority: extra
Section: gnome
Installed-Size: 914
Maintainer: denis <linvinus@gmail.com>
Architecture: amd64
Version: 0.4~rc19-linvinus1~xenial
Depends: libc6 (>= 2.14), libcairo2 (>= 1.2.4), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.9.10), libpango-1.0-0 (>= 1.14.0), libvte-2.91-0, libx11-6
Filename: pool/main/a/altyo/altyo_0.4~rc19-linvinus1~xenial_amd64.deb
Size: 227834
MD5sum: bb05233bdad616e30610a1d582a3d25d
SHA1: 28124afd8b53fe01bf45f110196859722f0c6b89
SHA256: 280c912f5311b43dec27d8112e9d906264d34c127f4a34aa2f1759d610648272
Description-en: AltYo - drop-down terminal emulator, written in vala, depends only on libvte and gtk3.
 AltYo - drop-down terminal emulator, written in vala, depends only on libvte and gtk3.
Description-md5: d03e0eeb56801b6d027058160034af03
