### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by thankjura** [linvinus/AltYo#73]
fatal: Не найден git репозитоий (или один из его каталогов вплоть до точки монтирования /var/tmp/portage)
Останавливаю поиск на границе файловой системы (так как GIT_DISCOVERY_ACROSS_FILESYSTEM не установлен).
grep: ./debian/changelog: Нет такого файла или каталога
#test -e ./altyo && rm ./altyo
/usr/bin/valac-0.36 -o altyo  -v --disable-warnings -X -DGETTEXT_PACKAGE=\"altyo\" -X -DAY_GIT_HASH=\"\" -X -DAY_CHANGELOG_TAG=\"\" --vapidir ./vapi --pkg gtk+-3.0 --pkg gdk-x11-3.0 --pkg cairo --pkg posix --pkg gmodule-2.0 -D VTE_2_91 --pkg vte-2.91 vapi/config.vapi vapi/xkb.vapi main.vala hvbox.vala altyo_terminal.vala altyo_window.vala altyo_hotkey.vala altyo_config.vala altyo_settings.vala data/altyo.c
Loaded package `/usr/share/vala-0.36/vapi/glib-2.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gobject-2.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gtk+-3.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gio-2.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/atk.vapi'
Loaded package `/usr/share/vala-0.36/vapi/cairo.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gdk-pixbuf-2.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gdk-3.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/pango.vapi'
Loaded package `/usr/share/vala-0.36/vapi/pangocairo.vapi'
Loaded package `/usr/share/vala-0.36/vapi/x11.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gdk-x11-3.0.vapi'
Loaded package `/usr/share/vala-0.36/vapi/posix.vapi'
Loaded package `/usr/share/vala-0.36/vapi/gmodule-2.0.vapi'
Loaded package `/usr/share/vala/vapi/vte-2.91.vapi'
altyo_window.vala:2894.99-2894.119: error: Argument 1: Cannot convert from `uint' to `int'
        string s = ( tab.tbutton.tab_title != null ? tab.tbutton.tab_title : _("index %d").printf(tab.tbutton.tab_index) );
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^
altyo_settings.vala:1636.107-1636.110: error: Argument 1: Cannot convert from `uint' to `int'
                string msg=_("New style will not be saved!\nin line %d  at position %d\nerror:%s").printf(line,pos,S);
                                                                                                          ^^^^
altyo_settings.vala:713.24-713.27: error: Argument 1: Cannot pass value to reference or output parameter
          store.remove(iter);
                       ^^^^
altyo_settings.vala:747.24-747.27: error: Argument 1: Cannot pass value to reference or output parameter
          store.remove(iter);
                       ^^^^
altyo_settings.vala:781.24-781.27: error: Argument 1: Cannot pass value to reference or output parameter
          store.remove(iter);
                       ^^^^
altyo_settings.vala:968.59-968.62: error: Argument 1: Cannot convert from `uint' to `int'
      msg=_("in line %d  at position %d error:%s").printf(line,pos,S);
                                                          ^^^^
Compilation failed: 6 error(s), 0 warning(s)
make: *** [Makefile:79: default] Ошибка 1

**Comment by Vistaus** [comment]
I can confirm that https://github.com/linvinus/AltYo/pull/78 fixes it.
